### ISSUE TITLE
TERMINOLOGY: 'process' instead of 'thread'

### ISSUE THREAD

**Issue by HenrikBengtsson** [fellstat/ipc#12]
Hi, nice package. I'd like to suggest that you use the term 'process' instead of 'thread', which I see you use in many places https://github.com/fellstat/ipc/search?q=thread&unscoped_q=thread.  A 'thread' is a very specific thing in operating systems and different from a 'process'.  In R, all user-facing parallel processing is done via multi-processing not multi-threading.  There are packages that use multi-threading _internally in native code_, e.g. data.table among several, but that is a different story.

**Comment by ifellows** [comment]
Great point. There is nothing specific in ipc having to do with threads, so the use of the term in the documentation is too loose. On the road now, but I’ll look to update shortly.
