### ISSUE TITLE
Progress indication when using future wrapper packages?

### ISSUE THREAD

**Issue by rpodcast** [fellstat/ipc#14]
I really enjoyed your [talk](https://resources.rstudio.com/rstudio-conf-2019/don-t-let-long-running-tasks-hang-your-users-introducing-ipc-for-shiny) at `rstudio::conf` and I'm so glad I had a front-row seat!  

I am scoping out how I can use `ipc` in one of my apps at work.  Within this app I am using the [`furrr`](https://davisvaughan.github.io/furrr/) package so I can execute [`future_pmap`](https://davisvaughan.github.io/furrr/reference/future_map2.html) on a data frame, spreading the rows on multiple CPU cores via `plan(multicore)`.  In the [progress example app](https://github.com/fellstat/ipc/blob/335ca5708fd81d10a718f3757fdf89be5522998c/inst/apps/progress/app.R#L48-L79) I see the `progress` object was injected in the loop.  For using this inside `future_pmap` or any other `future_*` functions, should I ensure that the custom function can take the progress object as a parameter?  Just trying to see the best way of approaching this.

**Comment by ifellows** [comment]
So my understanding is that `future_pmap` is a blocking operation. If you execute this the Shiny process your entire server will be blocked until `future_pmap` returns, so the progress bar won't update.

You might try kicking off the call into a future and do something like:

```

progress <- AsyncProgress$new()
fut <- future({
    future_pmap(input_data, function(x){
        dosomething(x)
        progress$inc(1/10)
    }
})
then(fut, function(result){
      progress$close()
      dosomethingwiththeresult(result)
})
```

**Comment by rpodcast** [comment]
Thanks so much, @ifellows!  I tried this out in a simple app and it works.  It had not occurred to me that I could do the `future_pmap` call within a wrapper `future` call.  Here's a toy app below that uses your solution:

```r
library(shiny)
library(ipc)
library(future)
library(furrr)
library(promises)
library(tibble)

plan(multicore)

# Define UI for application
ui <- fluidPage(

    # Application title
    titlePanel("Using ipc with furrr"),
    
    # Sidebar
    sidebarLayout(
        sidebarPanel(
            actionButton('run', 'Run')
        ),
        
        # Show result
        mainPanel(
            verbatimTextOutput("result")
        )
    )
)

# Define server logic 
server <- function(input, output, session) {
    
    my_runinf <- function(...) {
        l <- list(...)
        res <- runif(l$n, l$min, l$max)
        return(res)
    }
    
    # A reactive value to hold output
    result_val <- reactiveVal()
    
    set.seed(123)
    
    df <- tibble(
        sim_id = 1:10,
        n = 40,
        min = 0,
        max = 1000
    )
    
    observeEvent(input$run, {
        result_val(NULL)
        
        # Create a progress bar
        progress <- AsyncProgress$new(message="Complex analysis")
        
        fut <- future({
            df2 <- df
            future_pmap(df2, function(sim_id, n, min, max){
                Sys.sleep(2)
                res <- my_runinf(n=n, min=min, max=max)
                progress$inc(1/10)
                return(res)
            })
        })
        
        then(fut, function(result) {
            progress$close()
            result_val(result)
        })
    })
    
    output$result <- renderPrint({
        req(result_val())
    })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

**Comment by ifellows** [comment]
Cool. That pattern would make a great blog post.
