### ISSUE TITLE
Issue with promises in Shiny

### ISSUE THREAD

**Issue by x1o** [fellstat/ipc#15]
`ipc` does not seem to work properly with promises in shiny.

Say, I have a long-running process `get_top_n_cars` which outputs a tibble. I would like to plot this tibble after the computations are finished, but also to stop the process at any time. For that I run `get_top_n_cars` in a `future` and `%...>%`-pipe it to ggplot; inside the body of the function there's a loop that checks for the arrival of a 'terminate' message and stops upon receiving one.

So this works in .GlobalEnv:

```
get_top_n_cars <- function(n = 10, message_queue = NULL) {
  if (!is.null(message_queue)) {
    message_queue$consumer$addHandler(function(s, m, e) {}, 'terminate')
  }
  for (i in 1:3) {
    if (
      !is.null(message_queue) &&
      'terminate' %in% names(message_queue$consumer$consume())
    ) {
      cat('Terminated.\n')
      break
    }
    cat(i, 'computing...\n')
    Sys.sleep(1)
  }
  cat('---\n')
  mtcars %>% rownames_to_column('name') %>% top_n(n, wt = mpg)
}

plan(multiprocess)

q <- shinyQueue()

future({ get_top_n_cars(10, q) }) %...>% {
    ggplot(., aes(x = reorder(name, mpg), y = mpg)) +
      geom_point() +
      geom_segment(aes(xend = name), yend = 0) +
      coord_flip() +
      labs(title = 'mtcars by mpg', x = 'car')
  } %...>% 
  print()

Sys.sleep(1)
q$producer$fire('terminate')
```

The output is

```
1 computing...
2 computing...
Terminated.
---
```

as expected.

However, in shiny the behaviour is different. This is the server code:

```
  q <- shinyQueue()
  
  output$mtcarsPlot <- renderPlot(
    {
      n <- input$n_top_cars
      future({
        get_top_n_cars(n, q)
      }) %...>% {
        ggplot(., aes(x = reorder(name, mpg), y = mpg)) +
          geom_point() +
          geom_segment(aes(xend = name), yend = 0) +
          coord_flip() +
          labs(title = 'mtcars by mpg', x = 'car')
      }
    },
    res = 92
  )
  
  observeEvent(input$stop_btn, {
    q$producer$fire('terminate')
  })
```

I expect `output$mtcarsPlot` to redraw every time `input$n_top_cars` is changed (that is the case). However, the 'terminate' message does not get caught by `get_top_n_cars`. Even if `input$stop_btn` is triggered and the 'terminate' message is sent, the loop always repeats 3 times. But the next time `input$n_top_cars` is triggered again, the loop immediately terminates.

```
---
1 computing...
2 computing...
3 computing...
---
Terminated.
---
```

Please, see the full [app.R.](https://pastebin.com/9S4ti3D5).

**Comment by ifellows** [comment]
When you return a future (or promise) as the value of a reactive statement, Shiny will halt all computation until it is resolved. This will essentially freeze the UI for the user while the plot is being drawn. For this reason, you will almost always want to return `NULL` and not the promise. I think you want something like:

```r
server <- function(input, output) {
    L <- LongRunningComputation$new()
    
    q <- shinyQueue()
    
    plt <- reactiveVal(NULL)
    observeEvent(input$n_top_cars, {
        n <- input$n_top_cars
        future({
            L$get_top_n_cars(n, q)
        }) %...>% {
            plt(ggplot(., aes(x = reorder(name, mpg), y = mpg)) +
                geom_point() +
                geom_segment(aes(xend = name), yend = 0) +
                coord_flip() +
                labs(title = 'mtcars by mpg', x = 'car'))
        }
        NULL
    })
    output$mtcarsPlot <- renderPlot(plt(), res = 92)
    
    observeEvent(input$stop_btn, {
        q$producer$fire('terminate')
    })
}

```

**Comment by x1o** [comment]
Ian, that worked, thank you very much for the quick reply.

I was confused initially by the shiny authors' claim that `render*` function can work directly with futures / promises -- it makes little sense if the UI gets blocked until the future / promise is resolved.

**Comment by ifellows** [comment]
You may want to take another look at the Shiny Async documentation. The key point when a future is returned is that other people connected to the app are not blocked by the computation.
