### ISSUE TITLE
ipc package in Anaconda repository

### ISSUE THREAD

**Issue by hherrada** [fellstat/ipc#17]
Good morning, Ian. Thanks for the ipc package! At my company we use conda for package/environment management. We keep our own Anaconda repository and we've been trying to build the package to make it available to our internal R community. Unfortunately, we have not been able to build it. I noticed that the package is not available in the public anaconda.org, which makes me think that ipc might not be ready for conda. Do you happen to have any insight on this? Thank you

**Comment by ifellows** [comment]
I honestly don't have any idea. The easiest way to get ipc is usually to install from CRAN. I don't know who maintains the R packages on anaconda, or what their process is for inclusion. Is Anaconda the only way that packages are shared/distributed at your company?

**Comment by wlandau** [comment]
@brendanf put drake and txtq on conda-forge. Perhaps he can help here?

**Comment by brendanf** [comment]
@hherrada What build process did you try?  This [worked fine for me](https://anaconda.org/bfurneaux/r-ipc):

```
conda skeleton cran ipc
cd r-ipc
conda build .
```

If you're running entirely from a local repository, maybe the problem is that dependencies aren't available? (e.g., `r-txtq`)

**Comment by hherrada** [comment]
Thank you all for the prompt replies. Our internal Anaconda repository is the only way out tech and legal departments allow us to use open-source packages. Packages are made available in anaconda prod once approved by legal. Tomorrow, I’ll reach out to our anaconda tech team to obtain details on where the build is failing. I’ll share these as soon as I have them. Thanks!

**Comment by brendanf** [comment]
@ifellows If you are interested in distributing this or other packages via conda, putting packages on conda-forge is relatively simple.  For recipes that are already on CRAN, there is a [helper script](https://github.com/bgruening/conda_r_skeleton_helper) that does most of the work.  However, it is one more step to go through every time you release a new version.
