### ISSUE TITLE
a method to clean the queue

### ISSUE THREAD

**Issue by otoomet** [fellstat/ipc#18]
Can a method to clean the queue to be added, something like
```
queue$clean()
```
This may be useful for long-running processes.  Note that such methods exist in `txtq` package.

**Comment by ifellows** [comment]
By default `TextFileSource` will auto clean the file once it reaches 100 lines and all messages have been read. So If you've got a long running process the file will maintain a limited size under normal working conditions. See:

https://github.com/fellstat/ipc/blob/6d921c6e0da8c09ce93528af499b5d222a19f62d/R/text-file-source.R#L14

For other sources, it may not be clear what "clean" means or possible to execute a "clean." It would therefore not be wise to add a clean method at the queue level.

**Comment by otoomet** [comment]
Thanks.
I was thinking something like what txtq does, but yes, upper limit of the number of messages might do it.  There may be a need to remove unread messages too, although this is not relevant to my application.

Want to add a line or do about this behavior in docs?
