### ISSUE TITLE
Unhelpful error message when umask disable directory writing

### ISSUE THREAD

**Issue by otoomet** [fellstat/ipc#19]
Consider the following tiny example:
```
Sys.umask("100")  # disable owner's write permission
q <- ipc::queue()
```
This results in the following error message:
```
Error in filelock::lock(private$lock_file) : 
  Cannot open lock file: Permission denied
Calls: <Anonymous> ... <Anonymous> -> <Anonymous> -> <Anonymous> -> <Anonymous>
Error in filelock::unlock(lock) : 
  VECTOR_ELT() can only be applied to a 'list', not a 'closure'
Calls: <Anonymous> ... <Anonymous> -> <Anonymous> -> <Anonymous> -> <Anonymous>
Execution halted
```

I expect this to
a) tell something useful, e.g. "cannot create lockfile <lockfile name>, ensure you have write permission in <folder name>"
b) something in the docs that explains how the data is stored and what kind of permissions are needed.  It is not immediately obvious that we need certain directory permissions.

**Comment by ifellows** [comment]
If the error messages need to be improved, it should probably be done in the `txtq` package. I'm a bit ambivalent as that error message actually does tell you that there is a file permission issue.

I'm happy to have improved documentation. Pull requests in this area (and others) are greatly appreciated.

**Comment by otoomet** [comment]
Yes, I guess the error message is `txtq` issue.  It gives a hint, true, but it still took me 2hrs to figure it out...  the problem was that `/tmp/Rtmp...` was created with correct permissions, but inside it the `txtq` folder had wrong permissions.  And I had little clue what is needed and where, I even did not know that the subfolder belonges to `txtq`.  I'll think about how to document this but it may take a few weeks before I can again spend a day on the project.

Thanks anyway!
