### ISSUE TITLE
[JOSS-review] LICENSE - Content

### ISSUE THREAD

**Issue by JohnCoene** [fellstat/ipc#2]
The `LICENSE` file needs to include content.

related to https://github.com/openjournals/joss-reviews/issues/988

**Comment by ifellows** [comment]
CRAN is _very particular_ with regard to LICENSE file formats. I've added a LICENCE file with the full MIT license.

**Comment by mschubert** [comment]
What's the issue with having one LICENSE file recognized by CRAN *and* Github?

**Comment by ifellows** [comment]
For CRAN: The MIT license is a template, with the date and author needing to be specified. How they want this done is with "MIT + file LICENSE" in the description and the template parameters (and only the template parameters) specified in the LICENSE file.

Sometimes you just have to jump through the hoops they put in front of you.

**Comment by JohnCoene** [comment]
This could be because there are now two `LICENSE` file.
