### ISSUE TITLE
Show elapsed time

### ISSUE THREAD

**Issue by mattantaliss** [fellstat/ipc#22]
I am struggling to find any way to show elapsed time in an AsyncProgress bar. What I was hoping to be able to do is include the elapsed time in the message and have it ticking up every second. I thought the 'millis' value would dictate how often the message would update, but that doesn't seem to be the case. The best I can get is an updated value of elapsed time when I do the next 'set'.

Is it possible to periodically update a progress bar to show elapsed time ticking up while a function is processing?

**Comment by ifellows** [comment]
Progress bars have an endpoint. Elapsed time is open ended, so I don't know what a progress bar measuring elapsed time would look like. I also don't know why you would need to communicate with the child process to measure elapsed time. You can measure it from the shiny process and stop measuring it when the child process completes. Something like:

```r

initial_time <- reactiveVal(NULL) # set this to Sys.time() before you kick off job
current_time <- reactiveVal(NULL) # set to null when job is complete (perhaps using ipc)
work_complete <- reactiveVal(TRUE) # set to false before you kick off job. Set to true when complete (perhaps using ipc)

# call this just before you kick off the job
callback <- function (){
  if(work_complete()) return()
  current_time(Sys.time())
  later::later(callback, 1)
}

# ... do something with initial_time and current_time to display time elapsed to the user ... 
```

Note that callbacks will not be executed while Shiny is busy, so there isn't a way to assure that it will be executed at exactly every time interval.

**Comment by mattantaliss** [comment]
That is all helpful information.

My goal was to display the elapsed time in the progress bar's message, but the progress bar itself isn't changing value over time. It is, instead, being updated as steps of the process are completed. 

For example, if I have four distinguishable steps in a process (say, pulling data, processing it, compiling results, generating a report), I'll set the bar to have a value of 0.25, 0.50, 0.75, and 1 as I get to each block of code that is each of those steps, but the message I was hoping to display would be something like "Pulling Data (\<hh:mm:ss\>)" and would update the time elapsed each second as that step is executing.

**Comment by ifellows** [comment]
Here is an adapted version of the example from the vignette that counts seconds as the progress bar message:


```r
library(shiny)
library(ipc)
library(future)
library(promises)
plan(multisession)

ui <- fluidPage(
    
    titlePanel("Countdown"),
    
    sidebarLayout(
        sidebarPanel(
            actionButton('run', 'Run')
        ),
        
        mainPanel(
            tableOutput("result")
        )
    )
)

server <- function(input, output, session) {
    
    initial_time <- reactiveVal(NULL)

    # rewrite message every second as needed
    auto_inv <- reactiveTimer(1000)
    observe({
        auto_inv()
        if(!is.null(prog))
            prog$set(message = as.character(round(Sys.time() - initial_time())))
    })
    
    # A reactive value to hold output
    result_val <- reactiveVal()
    prog <- NULL
    # Handle button click
    observeEvent(input$run,{
        result_val(NULL)
        
        # Create a progress bar
        progress <- AsyncProgress$new(message="Complex analysis")
        prog <<- progress
        initial_time(Sys.time())
        future({
            for(i in 1:10){
                Sys.sleep(4)
                progress$inc(1/10) # Increment progress bar
            }
            data.frame(result="Insightful result")
        }) %...>% (function(result){
            result_val(result)  # Assign result of future to result_val
            prog <<- NULL
            progress$close()
        })
        # Return something other than the future so we don't block the UI
        NULL
    })
    
    # Set output to reactive value
    output$result <- renderTable({
        req(result_val())
    })
}

# Run the application
shinyApp(ui = ui, server = server)


```

**Comment by mattantaliss** [comment]
Thank you for that example. It was very helpful. I was able to take what you are showing there, adapt it to my specific code, and get the result I was after.

I do have one quick follow-up question: Is it possible to have a line break in a message?
