### ISSUE TITLE
NOTICE: plan(multiprocess) of future is deprecated

### ISSUE THREAD

**Issue by HenrikBengtsson** [fellstat/ipc#24]
Hi. Please note that `multiprocess` is [deprecated since future 1.20.0 (2020-11-03)](https://future.futureverse.org/news/index.html#future-1200) and will soon be defunct:

https://github.com/fellstat/ipc/search?q=multiprocess

**Comment by HenrikBengtsson** [comment]
Just a friendly reminder that `multiprocess` will become defunct and eventually be removed.  When that happens, your package will break and risk being archived on CRAN.  My suggestion is to update to use `multisession` instead.

**Comment by HenrikBengtsson** [comment]
I see you've done https://github.com/fellstat/ipc/commit/867bb8984da21db8c4623944a86fac827159a92c, but please note that there are more:

https://github.com/search?q=repo%3Afellstat%2Fipc+multiprocess&type=code

**Comment by ifellows** [comment]
Thank you. Right you are. Fixed. I'm testing non-cran dependent applications/packages now.

**Comment by HenrikBengtsson** [comment]
I see that **ipc** 0.1.4 is now on CRAN. I've just confirmed it's compatible with the upcoming **future** updates (https://github.com/HenrikBengtsson/future/commit/d70df1c2e18b21a64e11aa341172e9c4e7b5038f).  Thanks.

**Comment by ifellows** [comment]
Thanks Henrik!
