### ISSUE TITLE
[JOSS-review] Tests - coverage

### ISSUE THREAD

**Issue by JohnCoene** [fellstat/ipc#6]
I will check whether this is necessary but though the package includes unit tests which all pass when cloned and tested, because there is no continuous integration (i.e. [codecov](https://codecov.io/) or [coveralls](https://coveralls.io/)) it is not possible for me to know how much of the code is tested. 

related to https://github.com/openjournals/joss-reviews/issues/988

**Comment by ifellows** [comment]
Code coverage is not currently computed during CI. Continuous integration is done via Travis

https://travis-ci.org/fellstat/ipc

FYI, here is current test coverage:

```
> covr::package_coverage(type = "tests")
ipc Coverage: 39.66%
R/async-interrupt.R: 0.00%
R/async-progress.R: 0.00%
R/example.R: 0.00%
R/queue.R: 0.00%
R/redis-source.R: 92.59%
R/globals.R: 16.67%
R/consumer.R: 61.29%
R/producer.R: 61.54%
R/text-file-source.R: 92.59%
```

**Comment by mschubert** [comment]
FWIW, the way I interpret the JOSS guidelines is that automated test coverage calculation is not required. In this case, it would fall to the reviewers (*us*) to see if the tests present are sufficient.
